alpaca:
  key_id: "PK749QEISG5XKJ2M7BE6"
  secret_key: "q9WUen6lremQnKlOkCg05Rzsz9dcX8A8yFBe9Do1"
  base_url: "https://paper-api.alpaca.markets"

binance:
  api_key: "YOUR_BINANCE_KEY"
  api_secret: "YOUR_BINANCE_SECRET"

tradier:
  access_token: "YOUR_TRADIER_TOKEN"

assets:
  AAPL:
    type: equity
    strategy: rl_agent
    lot: 2000
  BTCUSD:
    type: crypto
    strategy: momentum
    lot: 5000
  SPY_20230915_400_C:
    type: option
    strategy: ml_ensemble
    lot: 1
